spring:
  application:
    name: micro-catalog-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalogdb?serverSelectionTimeoutMS=2000&retryWrites=false
  kafka:
    bootstrap-servers: localhost:9092

spring-book-topic-name: catalog-evt

#instance:
server:
  port: 8083

#eureka:
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
