spring:
  application:
    name: micro-catalog-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalogdb?serverSelectionTimeoutMS=2000&retryWrites=false
  kafka:
    bootstrap-servers: localhost:9092

spring-book-topic-name: catalog-evt

#instance:
server:
  port: 8083

# zipkin
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /actuator/catalogo

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}] %m%n"
#eureka:
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
