spring:
  application:
    name: micro-catalog-service
  data:
    mongodb:
      uri: mongodb://msvc-mongo:27017/catalogdb?serverSelectionTimeoutMS=2000&retryWrites=false
  kafka:
    bootstrap-servers: http://kafka-server:9092
  book-topic-name: catalog-evt

#instance:
server:
  port: 8083

#eureka:
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
