spring:
  application:
    name: micro-payment-service
  datasource:
    url: jdbc:mysql://msvc-mysql:3306/paymentdb
    username: root
    password: ImNotlol12msvc
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
#instance:
server:
  port: 8085