spring:
  application:
    name: micro-catalog-service
  data:
    mongodb:
      uri: mongodb://msvc-mongo:27017/catalogdb?serverSelectionTimeoutMS=2000&retryWrites=false
  kafka:
    bootstrap-servers: http://kafka-server:9092
  book-topic-name: catalog-evt


# zipkin
management:
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /actuator/catalogo
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}] %m%n"
    
#instance:
server:
  port: 8083

#eureka:
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
