spring:
  application:
    name: micro-book-service
  datasource:
    url: jdbc:mysql://msvc-mysql:3306/bookdb00
    username: root
    password: ImNotlol12msvc
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: http://kafka-server:9092
  book-topic-name: catalog-evt


# zipkin
management:
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /actuator/libros
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}] %m%n"
#Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

#instance:
server:
  port: 8082
